# Generated by Django 4.0 on 2022-07-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogsModel',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CommentsModel',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('blog_id', models.IntegerField()),
                ('comment', models.CharField(max_length=200)),
            ],
        ),
    ]
